
export const Projects = () => {
    return (
        <section
            id="projects"
            className="min-h-screen flex items-center justify-center py-20">
            <div className="max-w-5xl mx-auto px-4">
                <h2 className="text-3xl font-bold mb-8 text-center bg-gradient-to-r from-blue-500 to-purple-700 bg-clip-text text-transparent">
                    {""}
                    Featured Projects
                </h2>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div className="p-6 rounded-xl border border-white/10 hover:-translate-y-1 hover:border-blue-500/30 hover:shadow-[0_2px_8px_rgba(59,130,246,0.2)] transition">
                        <h3 className="text-xl font-bold mb-2 bg-gradient-to-r from-orange-400 via-lime-400 to-purple-700 bg-clip-text text-transparent">AI Generated Recipe App</h3>
                        <p className="text-slate-400 mb-4">
                            Users get the advantage of searching for their favorite meal recipes which are automatically generated by the Recipe API
                        </p>

                        <div className="flex flex-wrap gap-2 mb-4">
                            {["React Native", "Expo", "Node.js", "Express", "PestgreSQL Database ", "NeonDB"].map((tech, key) => (
                                <span
                                    key={key}
                                    className="bg-blue-500/10 text-blue-500 py-1 px-3 rounded-full text-sm hover:bg-blue-500/20
                                    hover:shadow-[0_2px_8px_rgba(59,130,246,0.1)] transition">
                                    {tech}
                                </span>
                            ))}
                        </div>

                        <div className="flex justify-between items-center">
                            <a
                                href="#"
                                className="my-4 text-lime-600 hover:text-violet-600 transition-colors">
                                {""}
                                View Project → {""}

                            </a>
                        </div>
                    </div>

                    <div className="p-6 rounded-xl border border-white/10 hover:-translate-y-1 hover:border-blue-500/30 hover:shadow-[0_2px_8px_rgba(59,130,246,0.2)] transition">
                        <h3 className="text-xl font-bold mb-2 bg-gradient-to-r from-orange-400 via-lime-400 to-purple-700 bg-clip-text text-transparent">AI Generated Recipe App</h3>
                        <p className="text-slate-400 mb-4">
                            Users get the advantage of searching for their favorite meal recipes which are automatically generated by the Recipe API
                        </p>

                        <div className="flex flex-wrap gap-2 mb-4">
                            {["React Native", "Expo", "Node.js", "Express", "PestgreSQL Database ", "NeonDB"].map((tech, key) => (
                                <span
                                    key={key}
                                    className="bg-blue-500/10 text-blue-500 py-1 px-3 rounded-full text-sm hover:bg-blue-500/20
                                    hover:shadow-[0_2px_8px_rgba(59,130,246,0.1)] transition">
                                    {tech}
                                </span>
                            ))}
                        </div>

                        <div className="flex justify-between items-center">
                            <a
                                href="#"
                                className="my-4 text-lime-600 hover:text-violet-600 transition-colors">
                                {""}
                                View Project → {""}

                            </a>
                        </div>
                    </div>

                    <div className="p-6 rounded-xl border border-white/10 hover:-translate-y-1 hover:border-blue-500/30 hover:shadow-[0_2px_8px_rgba(59,130,246,0.2)] transition">
                        <h3 className="text-xl font-bold mb-2 bg-gradient-to-r from-orange-400 via-lime-400 to-purple-700 bg-clip-text text-transparent">AI Generated Recipe App</h3>
                        <p className="text-slate-400 mb-4">
                            Users get the advantage of searching for their favorite meal recipes which are automatically generated by the Recipe API
                        </p>

                        <div className="flex flex-wrap gap-2 mb-4">
                            {["React Native", "Expo", "Node.js", "Express", "PestgreSQL Database ", "NeonDB"].map((tech, key) => (
                                <span
                                    key={key}
                                    className="bg-blue-500/10 text-blue-500 py-1 px-3 rounded-full text-sm hover:bg-blue-500/20
                                    hover:shadow-[0_2px_8px_rgba(59,130,246,0.1)] transition">
                                    {tech}
                                </span>
                            ))}
                        </div>

                        <div className="flex justify-between items-center">
                            <a
                                href="#"
                                className="my-4 text-lime-600 hover:text-violet-600 transition-colors">
                                {""}
                                View Project → {""}

                            </a>
                        </div>
                    </div>

                    <div className="p-6 rounded-xl border border-white/10 hover:-translate-y-1 hover:border-blue-500/30 hover:shadow-[0_2px_8px_rgba(59,130,246,0.2)] transition">
                        <h3 className="text-xl font-bold mb-2 bg-gradient-to-r from-orange-400 via-lime-400 to-purple-700 bg-clip-text text-transparent">AI Generated Recipe App</h3>
                        <p className="text-slate-400 mb-4">
                            Users get the advantage of searching for their favorite meal recipes which are automatically generated by the Recipe API
                        </p>

                        <div className="flex flex-wrap gap-2 mb-4">
                            {["React Native", "Expo", "Node.js", "Express", "PestgreSQL Database ", "NeonDB"].map((tech, key) => (
                                <span
                                    key={key}
                                    className="bg-blue-500/10 text-blue-500 py-1 px-3 rounded-full text-sm hover:bg-blue-500/20
                                    hover:shadow-[0_2px_8px_rgba(59,130,246,0.1)] transition">
                                    {tech}
                                </span>
                            ))}
                        </div>

                        <div className="flex justify-between items-center">
                            <a
                                href="#"
                                className="my-4 text-lime-600 hover:text-violet-600 transition-colors">
                                {""}
                                View Project → {""}

                            </a>
                        </div>
                    </div>

                    <div className="p-6 rounded-xl border border-white/10 hover:-translate-y-1 hover:border-blue-500/30 hover:shadow-[0_2px_8px_rgba(59,130,246,0.2)] transition">
                        <h3 className="text-xl font-bold mb-2 bg-gradient-to-r from-orange-400 via-lime-400 to-purple-700 bg-clip-text text-transparent">AI Generated Recipe App</h3>
                        <p className="text-slate-400 mb-4">
                            Users get the advantage of searching for their favorite meal recipes which are automatically generated by the Recipe API
                        </p>

                        <div className="flex flex-wrap gap-2 mb-4">
                            {["React Native", "Expo", "Node.js", "Express", "PestgreSQL Database ", "NeonDB"].map((tech, key) => (
                                <span
                                    key={key}
                                    className="bg-blue-500/10 text-blue-500 py-1 px-3 rounded-full text-sm hover:bg-blue-500/20
                                    hover:shadow-[0_2px_8px_rgba(59,130,246,0.1)] transition">
                                    {tech}
                                </span>
                            ))}
                        </div>

                        <div className="flex justify-between items-center">
                            <a
                                href="#"
                                className="my-4 text-lime-600 hover:text-violet-600 transition-colors">
                                {""}
                                View Project → {""}

                            </a>
                        </div>
                    </div>

                    <div className="p-6 rounded-xl border border-white/10 hover:-translate-y-1 hover:border-blue-500/30 hover:shadow-[0_2px_8px_rgba(59,130,246,0.2)] transition">
                        <h3 className="text-xl font-bold mb-2 bg-gradient-to-r from-orange-400 via-lime-400 to-purple-700 bg-clip-text text-transparent">AI Generated Recipe App</h3>
                        <p className="text-slate-400 mb-4">
                            Users get the advantage of searching for their favorite meal recipes which are automatically generated by the Recipe API
                        </p>

                        <div className="flex flex-wrap gap-2 mb-4">
                            {["React Native", "Expo", "Node.js", "Express", "PestgreSQL Database ", "NeonDB"].map((tech, key) => (
                                <span
                                    key={key}
                                    className="bg-blue-500/10 text-blue-500 py-1 px-3 rounded-full text-sm hover:bg-blue-500/20
                                    hover:shadow-[0_2px_8px_rgba(59,130,246,0.1)] transition">
                                    {tech}
                                </span>
                            ))}
                        </div>

                        <div className="flex justify-between items-center">
                            <a
                                href="#"
                                className="my-4 text-lime-600 hover:text-violet-600 transition-colors">
                                {""}
                                View Project → {""}

                            </a>
                        </div>
                    </div>

                    <div className="p-6 rounded-xl border border-white/10 hover:-translate-y-1 hover:border-blue-500/30 hover:shadow-[0_2px_8px_rgba(59,130,246,0.2)] transition">
                        <h3 className="text-xl font-bold mb-2 bg-gradient-to-r from-orange-400 via-lime-400 to-purple-700 bg-clip-text text-transparent">AI Generated Recipe App</h3>
                        <p className="text-slate-400 mb-4">
                            Users get the advantage of searching for their favorite meal recipes which are automatically generated by the Recipe API
                        </p>

                        <div className="flex flex-wrap gap-2 mb-4">
                            {["React Native", "Expo", "Node.js", "Express", "PestgreSQL Database ", "NeonDB"].map((tech, key) => (
                                <span
                                    key={key}
                                    className="bg-blue-500/10 text-blue-500 py-1 px-3 rounded-full text-sm hover:bg-blue-500/20
                                    hover:shadow-[0_2px_8px_rgba(59,130,246,0.1)] transition">
                                    {tech}
                                </span>
                            ))}
                        </div>

                        <div className="flex justify-between items-center">
                            <a
                                href="#"
                                className="my-4 text-lime-600 hover:text-violet-600 transition-colors">
                                {""}
                                View Project → {""}

                            </a>
                        </div>
                    </div>

                    

                </div>
            </div>

        </section>
    )
}